### ISSUE TITLE
How to configure this voice assistant in the Home Assistant interface

### ISSUE THREAD

**Issue by lboue** [m5stack/M5CoreS3-Esphome#13]
Does anyone know the procedure to use after the M5CoreS3 device has been registered in ESPHome to:
- configure this voice assistant in the Home Assistant interface
- launch this voice assistant

Help would be welcome for beginners.

I found these links that might help but I haven't managed to get it to work yet:
- [$13 voice assistant for Home Assistant](https://www.home-assistant.io/voice_control/thirteen-usd-voice-remote/#installing-the-software-onto-the-atom-echo)
- [ESP32-S3-BOX voice assistant](https://www.home-assistant.io/voice_control/s3_box_voice_assistant/)

**Comment by Forairaaaaa** [comment]
Hi, have you set up the [assist pipeline](https://www.home-assistant.io/voice_control/voice_remote_local_assistant)? After Assist and  ESPHome setup, CoreS3 should be able to do the same thing like the video in [ESP32-S3-BOX voice assistant](https://www.home-assistant.io/voice_control/s3_box_voice_assistant/)

**Comment by lboue** [comment]
Yes I set up the [assist pipeline](https://www.home-assistant.io/voice_control/voice_remote_local_assistant) with add-ons:
1. [Whisper](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_whisper)
2. [Piper](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_piper)
3. [openWakeWord](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_openwakeword)

**Comment by lboue** [comment]
Hello,

 I set up the [assist pipeline](https://www.home-assistant.io/voice_control/voice_remote_local_assistant) with add-ons:
1. [Whisper](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_whisper)
2. [Piper](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_piper)
3. [openWakeWord](https://my.home-assistant.io/redirect/supervisor_addon?addon=core_openwakeword)

It's still waiting for a wake-up call and nothing happens on the screen (the status icon doesn't change) when I say “hey Nabu”.
