### ISSUE TITLE
`Web Tools Flash` is not working to flash `M5CoreS3-Esphome` firmware:

### ISSUE THREAD

**Issue by lboue** [m5stack/M5CoreS3-Esphome#16]
`Web Tools Flash` is not working to flash `M5CoreS3-Esphome` firmware:

## Steps to reproduce

1. Go to [M5CoreS3 HA voice Assistant webpage](https://docs.m5stack.com/en/guide/homeassistant/m5cores3/m5cores3_quick_start)
2. Click `Web Tools Flash` button
3. Select your device

![image](https://github.com/user-attachments/assets/48db7c0c-03c1-47de-8d47-98dabe4865c4)

The file content is incorrect:

https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/static/esp-web-tools/cores3_voice_assistant.json

![image](https://github.com/user-attachments/assets/a4566456-19da-450f-a870-dda6c0839724)

**Comment by Tinyu-Zhao** [comment]
My colleague just fixed this issue, thanks for your feedback.
<img width="859" alt="image" src="https://github.com/user-attachments/assets/d4660263-b223-407a-bde1-30d5ae30a014">

**Comment by lboue** [comment]
Thanks @Tinyu-Zhao
